dist: xenial
language: clojure
jdk:
  - openjdk8
  - openjdk11
  - openjdk-ea
cache:
  directories:
    - "$HOME/.lein"
    - "$HOME/.m2"
script:
  - lein cljfmt check
  - lein test
  - lein uberjar
after_success:
  - lein cloverage --codecov
  - bash <(curl -s https://codecov.io/bash) -f target/coverage/codecov.json
